minimumReleaseAgeExclude:
  - concurrently@10.0.4
  - morphicons@1.5.0
overrides:
  shell-quote: 1.9.0
  vite: "catalog:"
  vitest: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.8
  vitest: 4.1.10
  vite-plus: ^0.2.8
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
