minimumReleaseAgeExclude:
  - concurrently@10.0.4
  - morphicons@1.5.0
  - "@laravel/passkeys@0.4.0"
  - "@rolldown/binding-android-arm64@1.2.4"
  - "@rolldown/binding-darwin-arm64@1.2.4"
  - "@rolldown/binding-darwin-x64@1.2.4"
  - "@rolldown/binding-freebsd-x64@1.2.4"
  - "@rolldown/binding-linux-arm-gnueabihf@1.2.4"
  - "@rolldown/binding-linux-arm64-gnu@1.2.4"
  - "@rolldown/binding-linux-arm64-musl@1.2.4"
  - "@rolldown/binding-linux-ppc64-gnu@1.2.4"
  - "@rolldown/binding-linux-s390x-gnu@1.2.4"
  - "@rolldown/binding-linux-x64-gnu@1.2.4"
  - "@rolldown/binding-linux-x64-musl@1.2.4"
  - "@rolldown/binding-openharmony-arm64@1.2.4"
  - "@rolldown/binding-win32-arm64-msvc@1.2.4"
  - "@rolldown/binding-win32-x64-msvc@1.2.4"
  - rolldown@1.2.4
overrides:
  shell-quote: 1.9.0
  vite: "catalog:"
  vitest: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.8
  vitest: 4.1.10
  vite-plus: ^0.2.9
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
