minimumReleaseAgeExclude:
  - concurrently@10.0.4
overrides:
  shell-quote: 1.9.0
  vite: "catalog:"
  vitest: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: ^0.2.6
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
