name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  DB_DATABASE: testing_db
  DB_USERNAME: postgres
  DB_PASSWORD: secret

services:
  postgres:
    image: pgvector/pgvector:pg18
    env:
      POSTGRES_DB: testing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports: [ "5432:5432" ]
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --restart unless-stopped

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg18
        env:
          POSTGRES_DB: testing_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --restart unless-stopped
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.5'
        extensions: pgsql, pcov
        coverage: xdebug
        tools: composer
    
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: composer-
    
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress
    
    - name: Generate application key
      run: php artisan key:generate
    
    - name: Create databases
      run: |
        touch .env
        echo "DB_CONNECTION=pgsql" >> .env
        echo "DB_HOST=${{ env.DB_HOST }}" >> .env
        echo "DB_PORT=${{ env.DB_PORT }}" >> .env
        echo "DB_DATABASE=${{ env.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ env.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
        php artisan migrate --graceful --force
    
    - name: Set up pcov
      run: |
        echo "pcov.enabled=1" >> phpunit.xml
        echo "<coverage processUncoveredFiles='true'>" >> phpunit.xml
        echo "  <groups>" >> phpunit.xml
        echo "    <group>default</group>" >> phpunit.xml
        echo "  </groups>" >> phpunit.xml
        echo "</coverage>" >> phpunit.xml
    
    - name: Run tests with coverage
      run: vendor/bin/phpunit --coverage-text --coverage-min=80
